package HospitalSystems;

/**
 *
 * @author TONMOY
 */
public class LogIn_Page extends javax.swing.JFrame {

    /**
     * Creates new form LogIn_Page
     */
    public LogIn_Page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back_panel = new javax.swing.JPanel();
        welcome_panel = new javax.swing.JPanel();
        login_panel = new javax.swing.JPanel();
        user_label = new javax.swing.JLabel();
        user_passLabel = new javax.swing.JLabel();
        userid_field = new javax.swing.JTextField();
        userpass_field = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        login_button = new javax.swing.JButton();
        alternate_tip = new javax.swing.JTextField();
        guest_button = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        back_imageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hospital Management System");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcome_panel.setBackground(new java.awt.Color(0, 0, 0));
        welcome_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        login_panel.setBackground(new java.awt.Color(31, 33, 35));
        login_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        user_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        user_label.setForeground(new java.awt.Color(255, 255, 255));
        user_label.setText("User ID");
        login_panel.add(user_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 98, 76, 33));

        user_passLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        user_passLabel.setForeground(new java.awt.Color(255, 255, 255));
        user_passLabel.setText("Password");
        login_panel.add(user_passLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 192, 76, 33));

        userid_field.setBackground(new java.awt.Color(31, 33, 35));
        userid_field.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        userid_field.setForeground(new java.awt.Color(255, 255, 255));
        userid_field.setBorder(null);
        userid_field.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        login_panel.add(userid_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 137, 270, 22));

        userpass_field.setBackground(new java.awt.Color(31, 33, 35));
        userpass_field.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        userpass_field.setForeground(new java.awt.Color(255, 255, 255));
        userpass_field.setBorder(null);
        login_panel.add(userpass_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 231, 270, 21));
        login_panel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 165, 270, 15));
        login_panel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 258, 270, 14));

        login_button.setBackground(new java.awt.Color(127, 86, 193));
        login_button.setText("Log In");
        login_button.setToolTipText("Log In");
        login_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        login_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_buttonActionPerformed(evt);
            }
        });
        login_panel.add(login_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, -1, -1));

        alternate_tip.setEditable(false);
        alternate_tip.setBackground(new java.awt.Color(31, 33, 35));
        alternate_tip.setForeground(new java.awt.Color(204, 0, 51));
        alternate_tip.setText("Don't Have a account?");
        alternate_tip.setBorder(null);
        login_panel.add(alternate_tip, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 356, -1, 29));

        guest_button.setBackground(new java.awt.Color(31, 33, 35));
        guest_button.setText("Guest Login");
        guest_button.setBorder(null);
        guest_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        login_panel.add(guest_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 394, 68, 23));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(31, 33, 35));
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setText("or,");
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        login_panel.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 398, 22, -1));

        jButton1.setBackground(new java.awt.Color(127, 86, 193));
        jButton1.setText("Create Account?");
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        login_panel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 391, 130, 28));

        welcome_panel.add(login_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, -1, 473));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Welcome");
        welcome_panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 270, 50));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(128, 214, 247));
        jLabel3.setText("We Believe \"Product non est aliquis perfricandus sit:\"");
        welcome_panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, 50));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("LOGO");
        welcome_panel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, -1, -1));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        welcome_panel.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 350, 10));

        back_imageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HospitalSystems/heartbeat.jpg"))); // NOI18N
        back_imageLabel.setText("Background Image");
        welcome_panel.add(back_imageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 800, -1));

        back_panel.add(welcome_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 605));

        getContentPane().add(back_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void login_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_buttonActionPerformed
        Login_logic login_obj = new Login_logic(userid_field.getText(), userpass_field.getText());
        this.setVisible(false);

    }//GEN-LAST:event_login_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alternate_tip;
    private javax.swing.JLabel back_imageLabel;
    private javax.swing.JPanel back_panel;
    private javax.swing.JButton guest_button;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton login_button;
    private javax.swing.JPanel login_panel;
    private javax.swing.JLabel user_label;
    private javax.swing.JLabel user_passLabel;
    private javax.swing.JTextField userid_field;
    private javax.swing.JPasswordField userpass_field;
    private javax.swing.JPanel welcome_panel;
    // End of variables declaration//GEN-END:variables
}
