/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HospitalSystems;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TONMOY
 */
public class Outdoor_Patient extends javax.swing.JFrame {

    /**
     * Creates new form Outdoo_Patient
     */
    public Outdoor_Patient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        infoPanel = new javax.swing.JPanel();
        addingPatientNameLabel = new javax.swing.JLabel();
        menutomainSeparator = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        dateLabel = new javax.swing.JLabel();
        dateTextfield = new javax.swing.JTextField();
        sidePanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        regPatient_Label = new javax.swing.JButton();
        outdoorPatient_Label = new javax.swing.JButton();
        indoorPatient_Label = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        OutdoorPatient_Table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        infoPanel.setBackground(new java.awt.Color(65, 65, 67));
        infoPanel.setPreferredSize(new java.awt.Dimension(850, 600));
        infoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addingPatientNameLabel.setBackground(new java.awt.Color(204, 0, 0));
        addingPatientNameLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addingPatientNameLabel.setForeground(new java.awt.Color(116, 249, 0));
        addingPatientNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addingPatientNameLabel.setText("OutDoor Patients");
        infoPanel.add(addingPatientNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 185, 28));

        menutomainSeparator.setBackground(new java.awt.Color(153, 153, 153));
        infoPanel.add(menutomainSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 10));

        jSeparator1.setBackground(new java.awt.Color(51, 0, 51));
        infoPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 56, 630, 10));

        dateLabel.setForeground(new java.awt.Color(116, 249, 0));
        dateLabel.setText("Date");
        infoPanel.add(dateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, 70, -1));

        dateTextfield.setEditable(false);
        dateTextfield.setText("Today's date..");
        dateTextfield.setBorder(null);
        infoPanel.add(dateTextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 30, 100, -1));

        sidePanel.setBackground(new java.awt.Color(0, 64, 81));

        jButton1.setBackground(new java.awt.Color(0, 64, 81));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HospitalSystems/Back_48px.png"))); // NOI18N
        jButton1.setBorder(null);

        regPatient_Label.setBackground(new java.awt.Color(116, 249, 0));
        regPatient_Label.setText("Register Patient");

        outdoorPatient_Label.setBackground(new java.awt.Color(116, 249, 0));
        outdoorPatient_Label.setText("Outdoor Patients");
        outdoorPatient_Label.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outdoorPatient_LabelActionPerformed(evt);
            }
        });

        indoorPatient_Label.setBackground(new java.awt.Color(116, 249, 0));
        indoorPatient_Label.setText("Indoor Patients");

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(regPatient_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(sidePanelLayout.createSequentialGroup()
                        .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(sidePanelLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jButton1))
                            .addGroup(sidePanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(outdoorPatient_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(indoorPatient_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(regPatient_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(outdoorPatient_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(indoorPatient_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(194, Short.MAX_VALUE))
        );

        infoPanel.add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 500));

        OutdoorPatient_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient ID", "Patient's Name", "Sex", "Age", "Consulting Doctor", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        OutdoorPatient_Table.setGridColor(new java.awt.Color(204, 204, 204));
        jScrollPane2.setViewportView(OutdoorPatient_Table);

        infoPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 640, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(infoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(infoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void outdoorPatient_LabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outdoorPatient_LabelActionPerformed
        // TODO add your handling code here:
        DefaultTableModel outdoor_model = (DefaultTableModel) OutdoorPatient_Table.getModel();
        /*outdoor_model.addRow(new Object[]{"Tonmoy", "Ishraq", "JOhnny"});
        outdoor_model.addRow(new Object[]{"Tonmoy", "Ishraq", "JOhnny"});*/
        
        try{
            File file_finder = new File("Management_files/PatientList");
            if(file_finder.isDirectory()){
                String[] listed_file = file_finder.list();
                System.out.println(listed_file[0]);
                
                
                for(int i = 0; i < listed_file.length; i++){
                    String current_file = "Management_files/PatientList" + "/" + listed_file[i];
                    try{
                        BufferedReader file_handler = new BufferedReader(new FileReader(current_file));
                        String fileName = file_handler.readLine();
                        LinkedList file_list = new LinkedList();
                        file_list.add(fileName);
                        
                        while(fileName != null){
                            fileName = file_handler.readLine();
                            file_list.add(fileName);
                            
                        }
                        String Rogir_prothomNam = (String)file_list.get(4);
                        String Rogir_lastNam = (String)file_list.get(5);
                        outdoor_model.addRow(new Object[]{file_list.get(2), Rogir_prothomNam + Rogir_lastNam, file_list.get(10), file_list.get(7), file_list.get(3), file_list.get(0)});
                        
                    }catch(Exception e){
                        JOptionPane.showMessageDialog(null, "Kicchu hoy nai -_-");
                    }
                }
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "A kemon File :/ ");
        }
        
        
        
        
    }//GEN-LAST:event_outdoorPatient_LabelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Outdoor_Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Outdoor_Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Outdoor_Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Outdoor_Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Outdoor_Patient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable OutdoorPatient_Table;
    private javax.swing.JLabel addingPatientNameLabel;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JTextField dateTextfield;
    private javax.swing.JButton indoorPatient_Label;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator menutomainSeparator;
    private javax.swing.JButton outdoorPatient_Label;
    private javax.swing.JButton regPatient_Label;
    private javax.swing.JPanel sidePanel;
    // End of variables declaration//GEN-END:variables
}
